import express, { Application, Router } from "express";
import { ApiMethods } from "./Api";
import { Manifest } from "./Manifest";
import { Renderer, RendererType } from "./Renderer";
import { IConfig, IonAppConfigWithName } from "./Config";
export declare class Server {
    readonly host: string;
    readonly port: number;
    readonly expressApp: Application;
    readonly apps: ConfiguredApps;
    readonly manifest: Manifest;
    readonly apiRouter: express.Router;
    private readonly _flatApiTree;
    private readonly _clientApiInfo;
    private readonly _renderers;
    private _httpServer;
    private _isListening;
    constructor();
    readonly callApi: (url: string, method: ApiMethods, data: any, req: express.Request, res: express.Response) => Promise<any>;
    private initializeRoutes;
    protected setRenderer<T extends Renderer>(app: AppName, rendererType: RendererType<T>): void;
    protected configureSession({ server, apps, database }: IConfig): void;
    private configureApi;
    protected configureApps({ apps }: IConfig): ConfiguredApps;
    protected init(): any;
    protected onListening(): void;
    protected onClose(): void;
    /**
     * gets called from the dev environment or the bundled backend (generated by the cli)
     */
    private readonly listen;
    readonly close: () => Promise<void>;
}
declare type AppName = keyof (typeof import("../../../ion.json"))["apps"];
declare type ConfiguredApps = {
    readonly [K in AppName]: Readonly<{
        config: IonAppConfigWithName;
        renderer: RendererType<any>;
        router: Router;
    }>;
};
export {};
